environment:
  PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
  
  matrix:
    - GENERATOR: Visual Studio 14 2015
      CONFIG: Release
      SHARED_LIBS: OFF
      ARCH: x86

    # x64 builds
    - GENERATOR: Visual Studio 14 2015 Win64
      CONFIG: Release
      SHARED_LIBS: OFF
      ARCH: x64

init:
  # update mysy2
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S autoconf perl"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S git"
  
before_build:
  - bash autogen.sh
  - set /p VER=<VERSION
  - set DIST_NAME=LibreSSL_%VER%_%ARCH%
  - mkdir build
  - cd build
  - cmake .. -G "%GENERATOR%" -DBUILD_SHARED_LIBS=%SHARED_LIBS% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\%DIST_NAME%

build_script:
  - cmake --build . --config %CONFIG%

test_script:
  # TODO: Determine how to run ssltest on AppVeyor
  - ctest -C %CONFIG% --timeout 150 --output-on-failure -E ssltest

after_test:
  - cmake --build . --target INSTALL
  - cd %APPVEYOR_BUILD_FOLDER%
  - copy COPYING %DIST_NAME%
  - copy ChangeLog %DIST_NAME%
  - 7z a %DIST_NAME%.zip %DIST_NAME%

artifacts:
  - path: '%DIST_NAME%.zip'
    name: '%DIST_NAME%'

